# Generated by Django 4.1.2 on 2022-11-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product_name',
            new_name='product',
        ),
    ]
