# Generated by Django 4.1.2 on 2022-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_rename_product_name_sales_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
