# Generated by Django 4.1.2 on 2022-10-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagory', '0002_alter_catogory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_img', models.ImageField(upload_to='product_img')),
                ('created_field', models.DateTimeField(auto_now_add=True)),
                ('modified_field', models.DateTimeField(auto_now=True)),
                ('catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagory.catogory')),
            ],
        ),
    ]
