# Generated by Django 4.1.2 on 2022-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
